"""Stage 5 — image generation.

Generates 4 images, all via Gemini's native image generation ("Nano Banana"):
  1. Exterior photorealistic render  (16:9)
  2. Interior photorealistic render  (16:9)
  3. 2D blueprint floor plan   — from exact solved room coordinates
  4. 3D dollhouse floor plan   — photorealistic re-render of the local
     isometric diagram (see below), so it matches #3's layout exactly

Imagen (imagen-4.0-generate-001 etc.) is not used: it was deprecated and
shut down 17 Aug 2026 — every 404 we saw from it was this, not an access
problem. Its replacement, gemini-3.1-flash-image, is called via
generate_content with response_modalities=[TEXT, IMAGE], not the old
generate_images/predict endpoint.

Keeping 2D and 3D consistent: blueprint_2d's prompt includes the exact solved
(x, y, width, length) for every room, so it reliably draws that layout.
floorplan_3d is generated by feeding Gemini the *local, deterministic*
isometric renderer's plain output as a reference image and asking it to
re-skin it photorealistically — this was tested against feeding it the flat
2D blueprint instead, which failed: Gemini kept preserving the flat top-down
camera angle instead of actually tilting to isometric, no matter how the
prompt was worded. Starting from an already-isometric reference sidesteps
that entirely and also guarantees the layout matches, since both the 2D
prompt and the 3D reference image are derived from the same room data.

Fallback chain per image: Gemini → Pollinations.ai (free, no key) →
(blueprint_2d/floorplan_3d only) local deterministic renderer.

All responses are returned as base64-encoded PNG strings.
"""

from __future__ import annotations

import asyncio
import base64
import urllib.parse
from typing import Any

import httpx
from google.genai import types as genai_types

from models.schemas import BuildableZone, CadastralData, FloorPlanAlternative
from stages.stage5_visualization.local_blueprint_renderer import render_blueprint_png
from stages.stage5_visualization.local_isometric_renderer import render_isometric_png
from stages.stage5_visualization.prompt_templates import (
    blueprint_2d_prompt,
    exterior_prompt,
    floorplan_3d_from_blueprint_prompt,
    floorplan_3d_prompt,
    interior_prompt,
)
from utils.gemini_client import get_client
from utils.logger import get_logger

_logger = get_logger("gemini_image_gen")

_IMAGE_MODEL = "gemini-3.1-flash-image"

_POLLINATIONS_DIMENSIONS: dict[str, tuple[int, int]] = {
    "exterior": (1280, 720),
    "interior": (1280, 720),
    "blueprint_2d": (1280, 960),
    "floorplan_3d": (1280, 720),
}
_POLLINATIONS_MAX_RETRIES = 2
_POLLINATIONS_TIMEOUT_SECONDS = 90.0


def _infer_floors(total_sqft: float, buildable_sqft: float) -> int:
    if buildable_sqft > 0 and total_sqft / buildable_sqft > 1.3:
        return 2
    return 1


def _find_living_room(alternative: FloorPlanAlternative) -> Any | None:
    for r in alternative.rooms:
        if "living" in r.name.lower():
            return r
    return alternative.rooms[0] if alternative.rooms else None


def _generate_gemini_image_sync(prompt: str) -> str:
    """Blocking call to Gemini's native image generation — runs in a thread pool."""
    client = get_client()
    response = client.models.generate_content(
        model=_IMAGE_MODEL,
        contents=prompt,
        config=genai_types.GenerateContentConfig(
            response_modalities=[genai_types.Modality.TEXT, genai_types.Modality.IMAGE],
        ),
    )
    for part in response.candidates[0].content.parts:
        if part.inline_data and part.inline_data.data:
            return base64.b64encode(part.inline_data.data).decode("utf-8")
    raise RuntimeError("Gemini image response contained no image data")


async def _generate_gemini_image(prompt: str, label: str) -> str:
    _logger.info("Generating %s image via %s", label, _IMAGE_MODEL)
    try:
        result = await asyncio.get_event_loop().run_in_executor(
            None, _generate_gemini_image_sync, prompt
        )
        _logger.info("%s image generated via Gemini (%d bytes base64)", label, len(result))
        return result
    except Exception as exc:
        _logger.error("Gemini image generation failed for %s: %s", label, exc)
        return ""


def _generate_gemini_image_with_reference_sync(prompt: str, reference_image_b64: str) -> str:
    """Blocking call to Gemini image generation, conditioned on a reference image.

    Used to generate the 3D dollhouse view from the already-generated 2D
    blueprint, so Gemini matches that exact layout instead of inventing a new
    one — this is what keeps 2D and 3D consistent with each other.
    """
    client = get_client()
    reference_part = genai_types.Part.from_bytes(
        data=base64.b64decode(reference_image_b64), mime_type="image/png"
    )
    response = client.models.generate_content(
        model=_IMAGE_MODEL,
        contents=[prompt, reference_part],
        config=genai_types.GenerateContentConfig(
            response_modalities=[genai_types.Modality.TEXT, genai_types.Modality.IMAGE],
        ),
    )
    for part in response.candidates[0].content.parts:
        if part.inline_data and part.inline_data.data:
            return base64.b64encode(part.inline_data.data).decode("utf-8")
    raise RuntimeError("Gemini image response contained no image data")


async def _generate_gemini_image_with_reference(
    prompt: str, reference_image_b64: str, label: str
) -> str:
    _logger.info("Generating %s image via %s, conditioned on 2D blueprint reference", label, _IMAGE_MODEL)
    try:
        result = await asyncio.get_event_loop().run_in_executor(
            None, _generate_gemini_image_with_reference_sync, prompt, reference_image_b64
        )
        _logger.info("%s image generated via Gemini (%d bytes base64)", label, len(result))
        return result
    except Exception as exc:
        _logger.error("Gemini reference-conditioned image generation failed for %s: %s", label, exc)
        return ""


async def _generate_pollinations_image(prompt: str, label: str) -> str:
    """Fallback image generation via Pollinations.ai — free, no API key required."""
    width, height = _POLLINATIONS_DIMENSIONS.get(label, (1024, 768))
    encoded_prompt = urllib.parse.quote(prompt[:500])
    url = (
        f"https://image.pollinations.ai/prompt/{encoded_prompt}"
        f"?width={width}&height={height}&nologo=true&model=flux"
    )

    for attempt in range(1, _POLLINATIONS_MAX_RETRIES + 1):
        _logger.info(
            "Falling back to Pollinations.ai for %s image (attempt %d/%d)",
            label, attempt, _POLLINATIONS_MAX_RETRIES,
        )
        try:
            async with httpx.AsyncClient(timeout=_POLLINATIONS_TIMEOUT_SECONDS) as client:
                response = await client.get(url)
                response.raise_for_status()
            result = base64.b64encode(response.content).decode("utf-8")
            _logger.info(
                "%s image generated via Pollinations (%d bytes base64)", label, len(result)
            )
            return result
        except Exception as exc:
            _logger.error(
                "Pollinations fallback failed for %s on attempt %d/%d: %s",
                label, attempt, _POLLINATIONS_MAX_RETRIES, exc,
            )

    return ""


async def generate_all_images(
    cadastral: CadastralData,
    zone: BuildableZone,
    alternative: FloorPlanAlternative,
) -> dict[str, str]:
    """Generates all 4 visualization images via Gemini, with fallbacks.

    blueprint_2d is generated first (from the exact solved room coordinates),
    then floorplan_3d is generated *conditioned on that blueprint image* so
    Gemini matches its layout instead of inventing an independent one — this
    is what keeps the 2D and 3D views showing the same house. exterior and
    interior are independent and run in parallel with the blueprint.

    Returns:
        dict with keys: exterior, interior, blueprint_2d, floorplan_3d
        Values are base64 PNG strings.
    """
    living = _find_living_room(alternative)
    floors = _infer_floors(alternative.total_built_area_sqft, zone.buildable_area_sqft)

    ext_prompt = exterior_prompt(
        district=cadastral.district,
        land_area_sqft=cadastral.land_area_sqft,
        orientation=cadastral.orientation,
        road_access_type=cadastral.road_access_type,
        total_built_area_sqft=alternative.total_built_area_sqft,
        buildable_area_sqft=zone.buildable_area_sqft,
        floors=floors,
    )
    int_prompt = interior_prompt(
        living_room_width=living.width_ft if living else 14,
        living_room_length=living.length_ft if living else 18,
        adjacencies=living.adjacencies if living else [],
        orientation=cadastral.orientation,
    )
    bp_prompt = blueprint_2d_prompt(
        rooms=alternative.rooms,
        total_built_area_sqft=alternative.total_built_area_sqft,
    )

    # Stage 1: exterior, interior, blueprint_2d — independent, run together.
    stage1_prompts = {"exterior": ext_prompt, "interior": int_prompt, "blueprint_2d": bp_prompt}
    labels = list(stage1_prompts.keys())
    gemini_results = await asyncio.gather(
        *[_generate_gemini_image(stage1_prompts[label], label) for label in labels]
    )
    results = dict(zip(labels, gemini_results))

    missing = [label for label, value in results.items() if not value]
    if missing:
        fallback_results = await asyncio.gather(
            *[_generate_pollinations_image(stage1_prompts[label], label) for label in missing]
        )
        for label, value in zip(missing, fallback_results):
            results[label] = value

    if not results["blueprint_2d"]:
        _logger.info("Gemini and Pollinations both unavailable for blueprint_2d — using local renderer")
        results["blueprint_2d"] = render_blueprint_png(
            alternative.rooms, alternative.total_built_area_sqft, alternative.variant
        )

    # Stage 2: floorplan_3d, conditioned on a locally-rendered plain isometric
    # diagram (not the flat 2D blueprint) — the local render already has the
    # correct camera angle AND correct layout, so Gemini's job is just to
    # re-skin it photorealistically, which is far more reliable than asking
    # it to invent a 3D angle from a flat top-down reference (tested: it kept
    # just recoloring the flat image instead of actually tilting the view).
    local_iso_reference = render_isometric_png(
        alternative.rooms, alternative.total_built_area_sqft, alternative.variant
    )
    fp3d_reference_prompt = floorplan_3d_from_blueprint_prompt(rooms=alternative.rooms)
    floorplan_3d = await _generate_gemini_image_with_reference(
        fp3d_reference_prompt, local_iso_reference, "floorplan_3d"
    )

    if not floorplan_3d:
        _logger.info("Reference-conditioned 3D generation failed — retrying without reference image")
        floorplan_3d = await _generate_gemini_image(
            floorplan_3d_prompt(rooms=alternative.rooms), "floorplan_3d"
        )
    if not floorplan_3d:
        floorplan_3d = await _generate_pollinations_image(
            floorplan_3d_prompt(rooms=alternative.rooms), "floorplan_3d"
        )
    if not floorplan_3d:
        _logger.info("Gemini and Pollinations both unavailable for floorplan_3d — using local renderer")
        floorplan_3d = local_iso_reference or render_isometric_png(
            alternative.rooms, alternative.total_built_area_sqft, alternative.variant
        )

    results["floorplan_3d"] = floorplan_3d
    return results
